#!/usr/bin/env python3
"""
Download a large file, split it into parts, and upload each part as an
asset on a GitHub Release in this same repo. This avoids third-party
file hosts (Litterbox/Catbox/Pixeldrain) blocking uploads that come
from GitHub Actions' datacenter IPs - since this uses GitHub's own API
with your own repo token, there's no such block.

Requires a GitHub token with `contents: write` permission on this repo.
In a GitHub Actions workflow, the built-in ${{ secrets.GITHUB_TOKEN }}
already has this by default - no extra secret needed.

Faster download: if the source server supports HTTP Range requests
(most file hosts / CDNs do), the file is downloaded using several
parallel connections instead of one.

HLS / m3u8 support: if <file_url> is (or points to) an .m3u8 playlist,
it is downloaded and remuxed into a single file with ffmpeg first
(handling segment downloading and playlist-referenced decryption),
then that local file is split and uploaded exactly like any other
source. ffmpeg must be available on PATH - it's preinstalled on
GitHub Actions' ubuntu-latest runners.

Usage:
    python3 split_upload.py <file_url> [chunk_size_mb] [upload_workers] [download_connections]

Required environment variables:
    GITHUB_TOKEN      - a token with contents:write on the target repo
    GITHUB_REPOSITORY - "owner/repo" (GitHub Actions sets this automatically)

Example:
    python3 split_upload.py "https://example.com/file.zip" 100 4 8
    python3 split_upload.py "https://example.com/stream/index.m3u8" 100 4 8
"""

import sys
import os
import time
import shutil
import subprocess
import threading
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed

TEMP_DIR = "upload_parts"
LINKS_FILE = "direct_links.txt"

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "")  # "owner/repo"
GITHUB_API = "https://api.github.com"

session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
})

gh_session = requests.Session()
gh_session.headers.update({
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
})

_upload_lock = threading.Lock()  # GitHub release asset uploads: do one at a time to avoid 422 name clashes
_progress_lock = threading.Lock()
_total_downloaded = [0]
_last_progress_print = [0]
PROGRESS_EVERY_BYTES = 10 * 1024 * 1024  # print every 10MB downloaded

_release = {}  # filled in once by ensure_release()


def report_download_progress(nbytes):
    with _progress_lock:
        _total_downloaded[0] += nbytes
        if _total_downloaded[0] - _last_progress_print[0] >= PROGRESS_EVERY_BYTES:
            print(f"[download] {_total_downloaded[0] / (1024*1024):.1f} MB downloaded so far...", flush=True)
            _last_progress_print[0] = _total_downloaded[0]


def ensure_release():
    """Creates a new GitHub Release to attach parts to, and caches its info."""
    if _release:
        return _release

    if not GITHUB_TOKEN or not GITHUB_REPOSITORY:
        raise RuntimeError(
            "GITHUB_TOKEN and GITHUB_REPOSITORY environment variables are required. "
            "In GitHub Actions, pass GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}."
        )

    tag = f"split-upload-{int(time.time())}"
    payload = {
        "tag_name": tag,
        "name": f"Split upload {tag}",
        "body": "Automatically generated by split_upload.py",
        "draft": False,
        "prerelease": True,
    }
    r = gh_session.post(f"{GITHUB_API}/repos/{GITHUB_REPOSITORY}/releases", json=payload, timeout=30)
    r.raise_for_status()
    data = r.json()
    _release["id"] = data["id"]
    _release["upload_url"] = data["upload_url"].split("{")[0]  # strip the {?name,label} template
    _release["html_url"] = data["html_url"]
    print(f"[release] Created release {tag}: {_release['html_url']}", flush=True)
    return _release


def upload_asset_bytes(filepath, asset_name):
    """Generic asset upload helper: uploads filepath under asset_name on the release.
    Returns (success: bool, direct_link_or_error: str)."""
    release = ensure_release()
    start = time.time()
    with _upload_lock:  # GitHub release asset upload endpoint doesn't like concurrent uploads well
        with open(filepath, "rb") as f:
            r = gh_session.post(
                release["upload_url"],
                params={"name": asset_name},
                headers={"Content-Type": "application/octet-stream"},
                data=f,
                timeout=(15, 600),
            )
    elapsed = time.time() - start
    if r.status_code in (200, 201):
        data = r.json()
        link = data.get("browser_download_url")
        if link:
            print(f"[timing] Upload of {asset_name} took {elapsed:.0f}s", flush=True)
            return True, link
    return False, f"HTTP {r.status_code} after {elapsed:.0f}s: {r.text[:300]}"


def upload_github_release_asset(filepath, part_num):
    """Uploads a file as an asset on the shared release.
    Returns (success: bool, direct_link_or_error: str)."""
    filename = os.path.basename(filepath)
    return upload_asset_bytes(filepath, filename)


def upload_links_file(path, max_retries=4):
    """Uploads the direct_links.txt file itself as a release asset, so the
    ordered list of part links is also downloadable straight from the
    release page. Returns the browser_download_url, or None on failure."""
    print(f"[upload] Uploading {os.path.basename(path)} to GitHub Release...", flush=True)
    backoff = 5.0
    asset_name = os.path.basename(path)
    for attempt in range(1, max_retries + 1):
        try:
            ok, result = upload_asset_bytes(path, asset_name)
            if ok:
                print(f"[done] {asset_name}: {result}", flush=True)
                return result
            print(f"[warn] Attempt {attempt} for {asset_name} failed: {result}", flush=True)
            if "422" in result or "already_exists" in result.lower():
                # Name clash - suffix a counter and retry immediately
                asset_name = f"direct_links_{attempt}.txt"
                continue
        except requests.exceptions.Timeout:
            print(f"[warn] {asset_name} attempt {attempt}: connection timed out", flush=True)
        except Exception as e:
            print(f"[warn] Error uploading {asset_name} (attempt {attempt}): {e}", flush=True)
        time.sleep(backoff)
        backoff = min(backoff * 2, 60)
    return None


def upload_worker(part_num, filepath, max_retries=4):
    print(f"[upload] Starting upload of part {part_num} to GitHub Release...", flush=True)
    backoff = 5.0
    for attempt in range(1, max_retries + 1):
        try:
            ok, result = upload_github_release_asset(filepath, part_num)
            if ok:
                print(f"[done] Part {part_num}: {result}", flush=True)
                if os.path.exists(filepath):
                    os.remove(filepath)
                return part_num, result
            print(f"[warn] Attempt {attempt} for part {part_num} failed: {result}", flush=True)
            if "422" in result or "already_exists" in result.lower():
                # Rare name clash - regenerate a fresh unique filename and retry immediately
                new_path = filepath + f".{attempt}"
                os.rename(filepath, new_path)
                filepath = new_path
                continue
        except requests.exceptions.Timeout:
            print(f"[warn] Part {part_num} attempt {attempt}: connection timed out", flush=True)
        except Exception as e:
            print(f"[warn] Error uploading part {part_num} (attempt {attempt}): {e}", flush=True)
        time.sleep(backoff)
        backoff = min(backoff * 2, 60)
    if os.path.exists(filepath):
        os.remove(filepath)
    return part_num, None


def check_range_support(url):
    """Returns (supports_ranges: bool, total_size: int or None)."""
    try:
        r = session.head(url, timeout=(10, 20), allow_redirects=True)
        size = r.headers.get("Content-Length")
        accepts_ranges = r.headers.get("Accept-Ranges", "").lower() == "bytes"
        if not accepts_ranges and size:
            probe = session.get(url, headers={"Range": "bytes=0-0"}, timeout=(10, 20), stream=True)
            accepts_ranges = probe.status_code == 206
            probe.close()
        return accepts_ranges, (int(size) if size else None)
    except Exception:
        return False, None


def download_range(url, start, end, dest_path, part_num):
    headers = {"Range": f"bytes={start}-{end}"}
    with session.get(url, headers=headers, stream=True, timeout=(15, 60)) as r:
        r.raise_for_status()
        with open(dest_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=4 * 1024 * 1024):
                if not chunk:
                    continue
                f.write(chunk)
                report_download_progress(len(chunk))
    print(f"[download] Part {part_num} complete ({(end - start + 1) / (1024*1024):.1f} MB)", flush=True)
    return part_num, dest_path


def run_parallel_download(url, total_size, chunk_size, download_workers, upload_workers):
    num_parts = (total_size + chunk_size - 1) // chunk_size
    print(
        f"[download] Server supports parallel ranged downloads - "
        f"{num_parts} part(s), {download_workers} download connections",
        flush=True,
    )

    download_executor = ThreadPoolExecutor(max_workers=download_workers)
    upload_executor = ThreadPoolExecutor(max_workers=upload_workers)

    download_futures = []
    for part_num in range(1, num_parts + 1):
        start = (part_num - 1) * chunk_size
        end = min(start + chunk_size - 1, total_size - 1)
        dest_path = os.path.join(TEMP_DIR, f"part_{part_num:02d}.zip")
        fut = download_executor.submit(download_range, url, start, end, dest_path, part_num)
        download_futures.append(fut)

    upload_futures = []
    for fut in as_completed(download_futures):
        part_num, dest_path = fut.result()
        upload_futures.append(upload_executor.submit(upload_worker, part_num, dest_path))

    download_executor.shutdown(wait=True)

    results = []
    for fut in as_completed(upload_futures):
        res = fut.result()
        if res and res[1]:
            results.append(res)
        else:
            print("[error] One of the background uploads failed!", flush=True)

    upload_executor.shutdown(wait=True)
    return results


def run_sequential_download(url, chunk_size, upload_workers):
    print("[download] Server does not support ranged downloads - using a single stream", flush=True)

    upload_executor = ThreadPoolExecutor(max_workers=upload_workers)
    upload_futures = []

    part_num = 1
    current_size = 0

    with session.get(url, stream=True, timeout=(15, 60)) as r:
        r.raise_for_status()
        part_path = os.path.join(TEMP_DIR, f"part_{part_num:02d}.zip")
        part_file = open(part_path, "wb")
        try:
            for chunk in r.iter_content(chunk_size=4 * 1024 * 1024):
                if not chunk:
                    continue
                part_file.write(chunk)
                current_size += len(chunk)
                report_download_progress(len(chunk))

                if current_size >= chunk_size:
                    part_file.close()
                    print(f"[download] Part {part_num} complete ({current_size / (1024*1024):.1f} MB), queuing upload...", flush=True)
                    upload_futures.append(upload_executor.submit(upload_worker, part_num, part_path))
                    part_num += 1
                    current_size = 0
                    part_path = os.path.join(TEMP_DIR, f"part_{part_num:02d}.zip")
                    part_file = open(part_path, "wb")

            part_file.close()
            if current_size > 0:
                print(f"[download] Final part {part_num} complete ({current_size / (1024*1024):.1f} MB), queuing upload...", flush=True)
                upload_futures.append(upload_executor.submit(upload_worker, part_num, part_path))
            elif os.path.exists(part_path):
                os.remove(part_path)
        finally:
            if not part_file.closed:
                part_file.close()

    results = []
    for fut in as_completed(upload_futures):
        res = fut.result()
        if res and res[1]:
            results.append(res)
        else:
            print("[error] One of the background uploads failed!", flush=True)

    upload_executor.shutdown(wait=True)
    return results


# --------------------------------------------------------------------------
# HLS / m3u8 support
# --------------------------------------------------------------------------

def is_m3u8_url(url):
    """Detects an HLS playlist link: ends in .m3u8, or has it in the path/query
    (common when the link was extracted from a video player's network requests)."""
    path_only = url.split("?", 1)[0].split("#", 1)[0]
    return path_only.lower().endswith(".m3u8") or ".m3u8" in url.lower()


def download_hls_to_file(url, dest_path, referer=None):
    """Downloads an HLS (.m3u8) stream to a single local file using ffmpeg.
    Works for master or media playlists - ffmpeg handles segment downloading,
    playlist-referenced AES-128 decryption, and remuxing into one file.
    Requires ffmpeg on PATH (preinstalled on GitHub Actions ubuntu runners)."""
    if shutil.which("ffmpeg") is None:
        raise RuntimeError(
            "ffmpeg is required to download m3u8/HLS links but was not found on PATH. "
            "It's preinstalled on GitHub Actions ubuntu-latest runners; locally install it "
            "(e.g. `apt-get install -y ffmpeg` or `brew install ffmpeg`)."
        )

    print(f"[hls] Detected an m3u8 link - downloading the stream with ffmpeg -> {dest_path}", flush=True)

    headers = f"User-Agent: {session.headers['User-Agent']}\r\n"
    if referer:
        headers += f"Referer: {referer}\r\n"

    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "warning", "-stats",
        "-headers", headers,
        "-protocol_whitelist", "file,http,https,tcp,tls,crypto",
        "-i", url,
        "-c", "copy",
        "-bsf:a", "aac_adtstoasc",
        dest_path,
    ]

    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
    last_print = 0.0
    for line in proc.stdout:
        line = line.strip()
        if not line:
            continue
        now = time.time()
        if "time=" in line or "error" in line.lower():
            if now - last_print >= 5:
                print(f"[hls] {line}", flush=True)
                last_print = now
    proc.wait()

    if proc.returncode != 0 or not os.path.exists(dest_path) or os.path.getsize(dest_path) == 0:
        raise RuntimeError(f"ffmpeg failed to download the HLS stream (exit code {proc.returncode}).")

    size_mb = os.path.getsize(dest_path) / (1024 * 1024)
    print(f"[hls] Done - downloaded and remuxed {size_mb:.1f} MB", flush=True)
    return dest_path


def split_local_file_and_upload(local_path, chunk_size, upload_workers, part_ext=".mp4"):
    """Splits an already-downloaded local file into chunk_size parts and
    uploads each one as it's cut, reusing the same upload_worker used for
    the direct-download path."""
    total_size = os.path.getsize(local_path)
    num_parts = (total_size + chunk_size - 1) // chunk_size
    print(
        f"[split] Source is {total_size / (1024*1024):.1f} MB - splitting into "
        f"{num_parts} part(s) of up to {chunk_size / (1024*1024):.0f}MB",
        flush=True,
    )

    upload_executor = ThreadPoolExecutor(max_workers=upload_workers)
    upload_futures = []

    part_num = 1
    with open(local_path, "rb") as src:
        while True:
            chunk = src.read(chunk_size)
            if not chunk:
                break
            part_path = os.path.join(TEMP_DIR, f"part_{part_num:02d}{part_ext}")
            with open(part_path, "wb") as pf:
                pf.write(chunk)
            print(f"[split] Part {part_num} ready ({len(chunk) / (1024*1024):.1f} MB), queuing upload...", flush=True)
            upload_futures.append(upload_executor.submit(upload_worker, part_num, part_path))
            part_num += 1

    results = []
    for fut in as_completed(upload_futures):
        res = fut.result()
        if res and res[1]:
            results.append(res)
        else:
            print("[error] One of the background uploads failed!", flush=True)

    upload_executor.shutdown(wait=True)
    return results


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 split_upload.py <file_url_or_m3u8_link> [chunk_size_mb] [upload_workers] [download_connections]")
        print("Requires env vars GITHUB_TOKEN and GITHUB_REPOSITORY (owner/repo).")
        sys.exit(1)

    url = sys.argv[1]
    chunk_size_mb = int(sys.argv[2]) if len(sys.argv) > 2 else 100
    upload_workers = int(sys.argv[3]) if len(sys.argv) > 3 else 2  # GitHub release uploads are serialized anyway
    download_workers = int(sys.argv[4]) if len(sys.argv) > 4 else 8

    chunk_size = chunk_size_mb * 1024 * 1024
    os.makedirs(TEMP_DIR, exist_ok=True)

    print(
        f"Starting - chunk size {chunk_size_mb}MB - service: GitHub Release assets - "
        f"upload workers: {upload_workers} - download connections: {download_workers}",
        flush=True,
    )

    try:
        if is_m3u8_url(url):
            local_path = os.path.join(TEMP_DIR, "hls_source.mp4")
            download_hls_to_file(url, local_path)
            results = split_local_file_and_upload(local_path, chunk_size, upload_workers)
            if os.path.exists(local_path):
                os.remove(local_path)
        else:
            print("Checking source server capabilities...", flush=True)
            supports_ranges, total_size = check_range_support(url)
            if total_size:
                print(f"Source size: {total_size / (1024*1024):.1f} MB", flush=True)

            if supports_ranges and total_size:
                results = run_parallel_download(url, total_size, chunk_size, download_workers, upload_workers)
            else:
                results = run_sequential_download(url, chunk_size, upload_workers)
    except Exception as e:
        print(f"[error] Failed downloading the source file: {e}", flush=True)
        sys.exit(1)

    # Sort ascending by part number so the .txt (and the printed order) is
    # always Part 1, Part 2, Part 3, ... regardless of upload/finish order.
    results.sort(key=lambda x: x[0])

    with open(LINKS_FILE, "w", encoding="utf-8") as f:
        for num, link in results:
            f.write(f"{link}\n")

    # Also upload the links file itself as a release asset, so anyone
    # visiting the release page can grab the ordered list directly
    # without needing the Actions log.
    links_asset_url = upload_links_file(LINKS_FILE)
    if links_asset_url:
        print(f"[done] {LINKS_FILE}: {links_asset_url}", flush=True)
    else:
        print(f"[error] Failed to upload {LINKS_FILE} to the release (parts were still uploaded).", flush=True)

    if os.path.exists(TEMP_DIR):
        shutil.rmtree(TEMP_DIR, ignore_errors=True)

    print(f"[finished] All parts uploaded. Links saved to {LINKS_FILE}.", flush=True)


if __name__ == "__main__":
    main()
